### ISSUE TITLE
Add scaling memory & scaling disk  and restarting app capabilities

### ISSUE THREAD

**Issue by chambrid** [ibm-cloud-solutions/hubot-ibmcloud-app-management#10]
Currently we only allow the scaling of instances `hubot app scale [app] [num] - Scale app to a number of instances.`

```
NAME:
   scale - Change or view the instance count, disk space limit, and memory limit for an app

USAGE:
   cf scale APP_NAME [-i INSTANCES] [-k DISK] [-m MEMORY] [-f]

OPTIONS:
   -f      Force restart of app without prompt
   -i      Number of instances
   -k      Disk limit (e.g. 256M, 1024M, 1G)
   -m      Memory limit (e.g. 256M, 1024M, 1G)
```

cf scale allows you do the above we need to provide more options.

**Comment by JonHoughton** [comment]
@chambrid:  I'm thinking the best way to do this is to have a generic scale command:
   `hubot app scale [app]`.

We will show the user the current values for instances, disk and memory and then prompt for instances, prompt for disk, and prompt for memory.

Sound ok?

**Comment by chambrid** [comment]
works for me.

**Comment by JonHoughton** [comment]
In addition, we need to add a new command for restarting apps:
`hubot app restart [app]`.

It does exactly what you would expect:
- stops all instances of the app
- starts all instances of the app
