### ISSUE TITLE
Show logs not returning in Slack

### ISSUE THREAD

**Issue by jamesjong** [ibm-cloud-solutions/hubot-ibmcloud-app-management#12]
Logs are not returning in Slack.
For example:
app logs a-demo-app
Returns:
Checking on `a-demo-app` in the `bot` space. Change spaces using `space set [space_name]`.

No logs are ever shown.

**Comment by jamesjong** [comment]
Logged an issue with the cf nodejs client module.
https://github.com/IBM-Bluemix/cf-nodejs-client/issues/25

**Comment by clanzen** [comment]
Hi James.  I see your cf-nodejs-client issue is fixed, and I just successfully showed log messages for an app locally.  Can this issue be closed?

**Comment by chambrid** [comment]
closed.
